name: Trivy Scan

on:
  workflow_dispatch: 

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Scan Docker
      run: |
       docker run --rm aquasec/trivy image --exit-code 1 --severity CRITICAL grpc/go
      #docker run --rm aquasec/trivy image --severity CRITICAL grpc/go
      
